# Generated by Django 5.0.6 on 2024-07-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=100)),
                ("time", models.CharField(max_length=100)),
                ("stadium", models.CharField(max_length=100)),
                ("town", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("African Stars FC", "African Stars FC"),
                            ("Blue Waters FC", "Blue Waters FC"),
                            ("Civics FC", "Civics FC"),
                            ("Eshoke Chula Chula FC", "Eshoke Chula Chula FC"),
                            ("Khomas Nampol FC", "Khomas Nampol FC"),
                            ("KK Palace FC", "KK Palace FC"),
                            ("Okahandja United FC", "Okahandja United FC"),
                            ("Ongos FC", "Ongos FC"),
                            ("Tigers FC", "Tigers FC"),
                            ("Young African FC", "Young African FC"),
                            ("Young Brazilians FC", "Young Brazilians FC"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home_score", models.PositiveIntegerField()),
                ("away_score", models.PositiveIntegerField()),
                (
                    "fixture",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="home.fixture"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fixture",
            name="away",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_fixtures",
                to="home.team",
            ),
        ),
        migrations.AddField(
            model_name="fixture",
            name="home",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_fixtures",
                to="home.team",
            ),
        ),
    ]
