# Generated by Django 5.0.6 on 2024-07-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_fixture_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixture",
            name="time",
            field=models.TimeField(),
        ),
    ]
