# Generated by Django 5.0.6 on 2024-07-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_caf_news_nfacup_premiership_story_tv"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="logo",
            field=models.ImageField(default="", upload_to="team_logos/"),
            preserve_default=False,
        ),
    ]
