# Generated by Django 5.0.6 on 2024-07-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_player_alter_fixture_options_alter_team_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="assist",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="clean_sheet",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
