# Generated by Django 5.0.6 on 2024-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_player_assist_player_clean_sheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixture",
            name="fixture_month",
            field=models.CharField(
                choices=[
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                ],
                default="March",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
